# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6ecd3e200e73499c20cc6c03947ab4dc4cc3d9dfc4900276e02affc5e2322d5ad0325e87b2474c098524fce4f8f8e4b1a4c9e31ebca49c26d5afe04e7c3f0a

test:
  secret_key_base: d55c2eeb906b2f3624c5653fb15e061ae02a8b58431cf43e996546320ec1b491f2cc6ed844ae9f3b7b19e110afb1380db6e5d0b42bf0d984d23b010c1befe979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
